title: ISD Lab
description: Information Systems and Databases Laboratory
baseurl: ""
url: https://piazzai.github.io/jekyll-nagymaros

theme: jekyll-nagymaros

collections:
  authors:
    output: true
defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
plugins:
  - jekyll-datapage-generator

# Configuration for the jekyll-datapage_gen plugin
page_gen-dirs: true
page_gen:
  - data: 'staff'
    template: 'profile'
    name: 'url'



copyright: ISD LAB
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
