title: ISD Lab
description: Information Systems and Databases Laboratory
baseurl: ""
url: https://piazzai.github.io/jekyll-nagymaros

theme: jekyll-nagymaros

collections:
  authors:
    output: true


copyright: ISD LAB
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
