title: ISD Lab
description: Information Systems and Databases Laboratory
baseurl: ""
url: 

remote-theme: jekyll-nagymaros

collections:
  authors:
    output: true
defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author

plugins:
  - jekyll-datapage-generator
  - jekyll-seo-tag
  - jekyll-sitemap

# Configuration for the jekyll-datapage_gen plugin
page_gen-dirs: true
page_gen:
  - data: 'staff'
    template: 'profile'
    name: 'url'
    title: 'name'
  
  - data: 'news'
    template: 'article'
    name: 'date'
    title: 'title'

copyright: ISD LAB
indexing: true

permalink: pretty


exclude:
  - demo/
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md
